apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-service
  namespace: netflix-app
spec:
  type: LoadBalancer
  selector:
    app: netflix-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
